com:
  creatorblue:
    anno-filter: /druid/**, /user/login, /user/logout, /index.html, /user/captcha.jpg, /user/querySettings, /swagger-ui.html**, /webjars/**, /swagger-resources/**, /v2/**, /**/*.ttf, /**/*.woff, /**/*.js, /**/*.css, /**/*.jpg, /**/*.jpeg, /**/*.png, /**/*.git, /**/*.bmp, /doLogin, /logoutRest, /login-api/**, /index-api/**, /subject-api/**, /major-api/**, /pkginfo-api/**, /teacher-api/**, /trainee-story/**, /partner-api/**, /news-api/**, /cbeditor/**, /resourceCenter-api/**, /teachingCenter-api/**, /classroom-api/**, /dict-api/**, /questions-api/**, /examCenter-api/**, /testPaper-api/**, /paperExamine/**, /managementPanel-api/**, /activity/**, /site/**, /cloud-api/**, /wx/**
    baseUrl: http://locahost:9084/console
    file-upload-path: e:/uploads/
    file-access-path: /uploads
    cb-upload-paths: /default, /dict-img, /sys-user-img, /settings-img, /site-img, /avd-img, /news-img, /teacher-img, /stustar-img, /partner-img, /subject-img, /major-img, /pkg-img, /class-img, /classroom-img, /resource-data, /trainee-data, /activity-data, /signin-data, /activity-data/answer-discuss, /activity-data/vote-questionnaire, /activity-data/brainstorming, /activity-data/task, /question-data, /friend-data, /trainee-data/blog-bg-pic, /auxiliary-teaching-video
    cbeditor-image-path: cbeditor-image
    cbeditor-image-suffix: png, jpg, jpeg, gif
    cbeditor-media-path: cbeditor-media
    cbeditor-media-suffix: mp4, rmvb, avi, mp3, wav
    cbeditor-file-path: cbeditor-file
    cbeditor-file-suffix: rar, zip, doc, docx, ppt, pptx, xls, xlsx, txt
    redisFlag: false
    is-cors: true
    schedule-cluster: false
    schedule-autostart: true
    signName: 创蓝科技
    accessKeyId:
    accessKeySecret:
    defaultHeadImg: defaulthead.png
    defaultName: 游客
    loginBackUrl:
    qqAppId:
    qqAppKey:
    xlAppId:
    xlAppKey:
    wxAppId:
    wxAppKey:
    gitUrl: 
    gitTicket: 
    log-level: debug
#微信支付配置
weixin:
  #小程序appid
  appid:
  #APP端的appid
  app_appid: xx
  #小程序秘钥
  secret: 
  #商户号
  mchid: 
  #证书路径
  certurl: /cert/apiclient_cert.p12
  #商家端端保证金支付回调地址
  pc_notifyurl: 
  #平台端售后同意退款回调地址
  pc_refund_notifyurl: 
  #C端订单取消退款回调地址
  order_refund_notifyurl: 
  #商家端保证金退款回调地址
  pc_bond_refund_notifyurl: 
  #C端支付回调地址
  app_notifyurl: 
  #商户秘钥
  key: 
  #h5支付之后跳转地址
  redirect_url: 
server:
  port: 19999
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: xqtt2929
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  aop:
    proxy-target-class: true
  application:
    name: ossbar-stp-evgl
  main:
    allow-bean-definition-overriding: true
  datasource:
    # 可选：never、always
    initialization-mode: never
    schema: classpath:/db/ossbar-stp-schema-mysql.sql
    data: classpath:/db/ossbar-stp-data-mysql.sql
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      connection-init-sqls: set names utf8mb4;
      initial-size: 1
      max-active: 20
      max-open-prepared-statements: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      minIdle: 1
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        login-password: ossbar.com
        login-username: ossbar
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
    password: root
    sql-script-encoding: UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/creatorblue-stp-ossbar?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
    username: root
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: i18n/messages
    cache-duration: 3600
    encoding: UTF-8
  mvc:
    view:
      prefix: /
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/${server.servlet.context-path}/oauth/token
      logout: http://localhost:${server.port}/${server.servlet.context-path}/logoutRest
      client-id: ossbar-platform-core
      client-secret: s9sd8uf9ewj9egwejgewgj0
      user-authorization-uri: http://localhost:${server.port}/${server.servlet.context-path}/oauth/authorize
    resource:
      token-info-uri: http://localhost:${server.port}/${server.servlet.context-path}/oauth/check_token
logging:
  level:
    tk:
      mybatis:
        pagehelper:
          mapper: TRACE
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath*:mapper/**/*.xml
pagehelper:
  auto-dialect: true
  close-conn: true